const fs = require('fs');
const path = require('path');

// Extract ANGLE DLLs generated by mozangle into the windows/ folder
// so they can be bundled in the npm pack and installer distributions.

if (process.platform !== 'win32') {
    process.exit(0);
}

const rootDir = path.join(__dirname, '..');
const workspaceTargetDir = path.join(rootDir, '..', '..', 'target');
const localTargetDir = path.join(rootDir, 'target');

const destDir = path.join(rootDir, 'windows');

if (!fs.existsSync(destDir)) {
    fs.mkdirSync(destDir, { recursive: true });
}

let foundEgl = false;
const possibleTargetDirs = [localTargetDir, workspaceTargetDir];

for (const targetDir of possibleTargetDirs) {
    if (!fs.existsSync(targetDir)) continue;

    // We search recursively in the target directory for release/build/mozangle-*
    // because the exact path depends on the target triple used by cargo.

    // Instead of deep recursive search which could be slow, we'll check the typical targets:
    // target/release/build/mozangle-*
    // target/x86_64-pc-windows-msvc/release/build/mozangle-*

    const tryDirs = [
        path.join(targetDir, 'release', 'build'),
        path.join(targetDir, 'x86_64-pc-windows-msvc', 'release', 'build')
    ];

    for (const buildDir of tryDirs) {
        if (!fs.existsSync(buildDir)) continue;

        const entries = fs.readdirSync(buildDir, { withFileTypes: true });

        // Find all directories starting with mozangle-
        const mozangleDirs = entries
            .filter(e => e.isDirectory() && e.name.startsWith('mozangle-'))
            .map(e => path.join(buildDir, e.name))
            .sort((a, b) => fs.statSync(b).mtimeMs - fs.statSync(a).mtimeMs); // newest first

        for (const dir of mozangleDirs) {
            const outDir = path.join(dir, 'out');
            const eglSrc = path.join(outDir, 'libEGL.dll');
            const glesSrc = path.join(outDir, 'libGLESv2.dll');

            if (fs.existsSync(eglSrc) && fs.existsSync(glesSrc)) {
                fs.copyFileSync(eglSrc, path.join(destDir, 'libEGL.dll'));
                fs.copyFileSync(glesSrc, path.join(destDir, 'libGLESv2.dll'));

                const d3dSrc = path.join(outDir, 'd3dcompiler_47.dll');
                if (fs.existsSync(d3dSrc)) {
                    fs.copyFileSync(d3dSrc, path.join(destDir, 'd3dcompiler_47.dll'));
                }

                console.log(`Extracted ANGLE DLLs from ${outDir} to ${destDir}`);
                foundEgl = true;
                break;
            }
        }

        if (foundEgl) break;
    }

    if (foundEgl) break;
}

if (!foundEgl) {
    console.warn('\n====== WARNING ======');
    console.warn('libEGL.dll or libGLESv2.dll not found in the target directory!');
    console.warn('The "no-wgl" feature might not be enabled on libservo, or mozangle build failed.');
    console.warn('This is required for Windows rendering. The packaged application may fail to start.');
    console.warn('=====================\n');
    // We don't exit with 1 here because in some CI setups it's built separately, but we still warn.
    // wait, we probably DO want to exit 1 to fail the build if rendering will be broken.
    process.exit(1);
}
